# services:
#   namenode:
#     image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
#     container_name: namenode
#     restart: always
#     ports:
#       - 9870:9870
#     volumes:
#       - hadoop_namenode:/hadoop/dfs/name
#     environment:
#       - CLUSTER_NAME=test
#   datanode:
#     image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#     container_name: datanode
#     restart: always
#     volumes:
#       - hadoop_datanode:/hadoop/dfs/data
#     environment:
#       SERVICE_PRECONDITION: "namenode:9870"
# volumes:
#   hadoop_namenode:
#   hadoop_datanode:

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - C:\my_folder:/mnt/my_folder  # Добавленное монтирование
    environment:
      - CLUSTER_NAME=test

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"

volumes:
  hadoop_namenode:
  hadoop_datanode:

